<?php
/**
 * Training related posts template
 *
 * @var $block \Newance\Training\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()): ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()): ?>
        <div class="SectionTitle">
            <h2 class="Kilo u-marginBn">
                <span class="SectionTitle-inner"><?php echo __('Related Trainings'); ?></span>
            </h2>
        </div>

        <div class="Nav Nav--stacked Nav--trainingsCategories">
            <ul class="Nav-list">
                <?php foreach ($_postCollection as $_post): ?>
                    <li class="Nav-item">
                        <a class="Nav-link" href="<?php echo $_post->getPostUrl() ?>">
                            <span class="Nav-target"><?php echo $block->escapeHtml($_post->getTitle()) ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>
