<?php
/**
 * Training sidebar categories template
 *
 * @var $block \Newance\Training\Block\Sidebar\Categories
 */
?>

<?php $items = $this->getGroupedChilds(); ?>
<?php if (count($items)):  ?>
    <div class="Box Box--grey u-marginBmd">
        <div class="Grid Grid--withGutter">
            <?php $first = true; ?>
            <?php foreach ($items as $item): ?>
                <?php $level = $item->getLevel(); ?>

                <?php if ($level == 0): ?>
                    <?php if (!$first): ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="Grid-cell u-sm-size1of2 u-md-size1of2<?php if (!$first): ?> u-xs-marginTmd u-lg-marginTmd<?php endif; ?>">
                        <h2 class="u-marginBsm">
                            <?php echo $block->escapeHtml($item->getTitle()) ?>
                            <?php if ($block->showPostsCount()) { ?>
                                (<?php echo $block->escapeHtml($item->getPostsCount()) ?>)
                            <?php } ?>
                        </h2>
                        <div class="Nav Nav--stacked Nav--trainingCategories">
                            <ul class="Nav-list">
                <?php endif; ?>

                <?php if ($level > 0): ?>
                    <li class="Nav-item">
                        <a class="Nav-link" href="<?php echo $item->getCategoryUrl() ?>">
                            <span class="Nav-target"><?php echo $block->escapeHtml($item->getTitle()) ?></span>
                        </a>
                        <?php if ($block->showPostsCount()) { ?>
                            (<?php echo $block->escapeHtml($item->getPostsCount()) ?>)
                        <?php } ?>
                    </li>
                <?php endif; ?>

                <?php $first = false; ?>
            <?php endforeach; ?>

                    </ul>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>
