<?php
/**
 * Training sidebar recent posts template
 *
 * @var $block \Newance\Training\Block\Sidebar\Recent
 */
?>

<?php $_postCollection = $block->getPostCollection(); ?>
<?php if ($_postCollection->count()): ?>
    <div class="Box Box--grey u-marginBmd">
        <div class="Grid Grid--withGutter">
            <div class="Grid-cell u-sm-size1of2 u-md-size1of2">
                <h2 class="u-marginBsm"><?php echo __('Recent Posts') ?></h2>
                <div class="Nav Nav--stacked Nav--trainingCategories">
                    <ul class="Nav-list">
                        <?php foreach ($_postCollection as $_post): ?>
                            <li class="Nav-item">
                                <a class="Nav-link" href="<?php echo $_post->getPostUrl() ?>">
                                    <span class="Nav-target"><?php echo $block->escapeHtml($_post->getTitle()) ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
