<?php
/**
 * Training sidebar search form template
 *
 * @var $block \Newance\Training\Block\Sidebar\Search
 */
?>

<div class="Box Box--grey u-marginBmd">
    <form action="<?php echo $block->getFormUrl() ?>" method="get">
        <div class="Form-item u-marginBsm">
            <div class="Form-controls">
                <input class="Form-element Form-element--input" id="training_search" type="text" placeholder="<?php echo __('Search') ?>">
            </div>
        </div>

        <div class="Form-item Form-item--actions">
            <div class="Form-controls">
                <button onclick="return doSearch(this);" class="Button Button--primary" type="submit">
                    <?php echo __('Search') ?>
                </button>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function doSearch(e) {
        var value = document.getElementById('training_search').value;
        if (value) {
            window.location = e.form.action + value + '/';
        }
        return false;
    }
</script>
