<?php

// For Heroicons Outline
/** @var Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);


//For Heroicons Solid
/** @var Hyva\Theme\ViewModel\HeroiconsSolid $HeroiconsSolid */
$heroiconsSolid = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsSolid::class);

$ticketId = $this->getRequest()->getParam('id');
$ticketDetails = $block->getTicketDetails($ticketId);
$ticketStatusCode = $ticketDetails['status'];
$ticketAttachments = $block->getTicketAttachments($ticketDetails);
$ticketSubject = $block->getTicketSubject($ticketDetails);
$ticketDescription = $block->getTicketDescription($ticketDetails);
$ticketCreatedAt = $block->getTicketCreatedAt($ticketDetails);
$userName = $ticketDetails['requester_name'];
$ticketStatus = $block->getTicketStatus($ticketDetails);
$replyDetails = $block->getTicketReplyDetails($ticketId);
$replyMsg = __('Please enter a reply message.');
?>

<?php if ($ticketStatusCode !== 5) : ?>
    <div class="subscriberForm p-8 relative">
        <a href="<?= $block->getUrl('freshdesk/customer/close', ['id' => $ticketId]) ?>" class="absolute top-0 right-0 btn btn-primary rounded" title="<?= $block->escapeHtml(__('Close Ticket')) ?>"><?= $block->escapeHtml(__('Close Ticket')) ?></a>
    </div>
<?php endif; ?>
<div class="subscriberForm bg-container-darker p-8 mb-10 relative">
    <h2 class="text-gray-900 text-xl title-font font-medium mb-4"><?= $ticketSubject ?></h2>
    <span class="absolute top-4 right-4 pt-4 pr-4 flex"><?= $ticketStatus ?></span>
    <div class="text-gray-900 text-base font-medium mb-4 flex">
        <span><?= $ticketCreatedAt ?></span>
        <span class="pl-2 pr-2">|</span>
        <span><?= $userName; ?></span>
    </div>
    <?= $ticketDescription ?>
    <?php if (count($ticketAttachments) > 0) : ?>
        <div class="mx-auto mt-4 grid gap-4 grid-cols-1 sm:grid-cols-2 xl:grid-cols-3">
            <?php foreach ($ticketAttachments as $ticketAttachment) : ?>
                <div class="relative attachment p-2 border flex">
                    <?php if (strpos($ticketAttachment['content_type'], 'image/') === 0) : ?>
                        <div class="relative fileicon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="392">
                                <path fill="#ebeff3" d="M3.725.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304H27.09c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.856.991a1.294 1.294 0 00-.874-.34H3.725z" data-identifyElement="393"></path>
                                <path fill="#b1bdc8" d="M13.893 19.602c0 .925-.767 1.676-1.715 1.676-.946 0-1.713-.751-1.713-1.676s.767-1.676 1.713-1.676c.948 0 1.715.751 1.715 1.676zm-7.619 9.063h18.578c.418 0 .669-.456.438-.797l-5.848-8.658a.533.533 0 00-.895.027l-4.12 6.99a.531.531 0 01-.826.107l-2.865-2.8a.533.533 0 00-.755.011L5.89 27.799c-.315.328-.078.866.383.866z" data-identifyElement="394"></path>
                                <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="395"></path>
                                <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="396"></path>
                            </svg>
                            <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $block->getFileExtension($ticketAttachment['name']) ?></span>
                        </div>
                    <?php elseif (strpos($ticketAttachment['content_type'], 'application/pdf') === 0) : ?>
                        <div class="relative fileicon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="460">
                                <path fill="#ebeff3" d="M3.668.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304h23.365c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.799.991a1.294 1.294 0 00-.874-.34H3.668z" data-identifyElement="461"></path>
                                <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="462"></path>
                                <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="463"></path>
                                <path fill="#b1bdc8" d="M8.617 27.893v-9.387h.862c.16 0 .289-.131.289-.293s-.129-.293-.289-.293H7.176c-.16 0-.289.131-.289.293s.129.293.289.293h.862v9.387h-.862c-.16 0-.289.131-.289.293s.129.293.289.293h2.303c.16 0 .289-.131.289-.293s-.129-.293-.289-.293h-.862zm3.602-7.92c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219zm0 2.934c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219zm0 2.933c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219z" data-identifyElement="464"></path>
                            </svg>
                            <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $block->getFileExtension($ticketAttachment['name']) ?></span>
                        </div>
                    <?php else : ?>
                        <div class="relative fileicon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="367">
                                <path fill="#ebeff3" d="M3.668.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304h23.365c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.799.991a1.294 1.294 0 00-.874-.34H3.668z" data-identifyElement="368"></path>
                                <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="369"></path>
                                <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="370"></path>
                                <path fill="#b1bdc8" d="M16.921 17.8l-2.625 10.4c-.036.143.049.288.189.325s.283-.049.319-.192l2.625-10.4c.036-.143-.049-.288-.189-.325s-.283.049-.319.192zm3.997 5.126c.207.109.207.41.001.52l-2.586 1.379v1.293l4.738-2.691v-.481l-4.738-2.672v1.283l2.585 1.369zm-10.613.519a.296.296 0 01.001-.52l2.585-1.369v-1.283l-4.738 2.672v.481l4.738 2.691v-1.293l-2.586-1.379z" data-identifyElement="371"></path>
                            </svg>
                            <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $block->getFileExtension($ticketAttachment['name']) ?></span>
                        </div>
                    <?php endif; ?>
                    <div class="w-full p-4 file-name-size">
                        <span class="font-normal text-sm break-all"><?= $ticketAttachment['name']; ?></span><br />
                        <span class="font-normal text-sm"><?= $block->getBytesToKilobytes($ticketAttachment['size']) ?></span>
                    </div>
                    <div class="backlayer"></div>
                    <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 download-icon">
                        <a href="<?= $block->getUrl('freshdesk/customer/download', ['file' => urlencode($ticketAttachment['attachment_url']), 'name' => urlencode($ticketAttachment['name'])]) ?>" download>
                            <?= $heroicons->documentDownloadHtml('inline-block w-6 h-6 mr-1', 26, 26, ['title' => 'Download']); ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($replyDetails as $reply) : ?>
    <div class="subscriberForm bg-container-darker p-8 mb-10 relative">
        <?= $reply['body']; ?>
        <span class="absolute top-4 right-4 pt-4 pr-4"><?= $reply['updated_at']; ?></span>
        <?php $replyAttachments = $reply['attachments']; ?>
        <?php if (count($replyAttachments) > 0) : ?>
            <div class="mx-auto grid gap-4 grid-cols-1 sm:grid-cols-2 xl:grid-cols-3">
                <?php foreach ($replyAttachments as $replyAttachment) : ?>
                    <div class="relative attachment p-2 border flex ">
                        <?php if (strpos($replyAttachment['content_type'], 'image/') === 0) : ?>
                            <div class="relative fileicon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="392">
                                    <path fill="#ebeff3" d="M3.725.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304H27.09c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.856.991a1.294 1.294 0 00-.874-.34H3.725z" data-identifyElement="393"></path>
                                    <path fill="#b1bdc8" d="M13.893 19.602c0 .925-.767 1.676-1.715 1.676-.946 0-1.713-.751-1.713-1.676s.767-1.676 1.713-1.676c.948 0 1.715.751 1.715 1.676zm-7.619 9.063h18.578c.418 0 .669-.456.438-.797l-5.848-8.658a.533.533 0 00-.895.027l-4.12 6.99a.531.531 0 01-.826.107l-2.865-2.8a.533.533 0 00-.755.011L5.89 27.799c-.315.328-.078.866.383.866z" data-identifyElement="394"></path>
                                    <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="395"></path>
                                    <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="396"></path>
                                </svg>
                                <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $replyAttachment['type'] ?></span>
                            </div>
                        <?php elseif (strpos($replyAttachment['content_type'], 'application/pdf') === 0) : ?>
                            <div class="relative fileicon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="460">
                                    <path fill="#ebeff3" d="M3.668.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304h23.365c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.799.991a1.294 1.294 0 00-.874-.34H3.668z" data-identifyElement="461"></path>
                                    <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="462"></path>
                                    <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="463"></path>
                                    <path fill="#b1bdc8" d="M8.617 27.893v-9.387h.862c.16 0 .289-.131.289-.293s-.129-.293-.289-.293H7.176c-.16 0-.289.131-.289.293s.129.293.289.293h.862v9.387h-.862c-.16 0-.289.131-.289.293s.129.293.289.293h2.303c.16 0 .289-.131.289-.293s-.129-.293-.289-.293h-.862zm3.602-7.92c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219zm0 2.934c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219zm0 2.933c-.24 0-.434.197-.434.44s.194.44.434.44h12.083c.24 0 .434-.197.434-.44s-.194-.44-.434-.44H12.219z" data-identifyElement="464"></path>
                                </svg>
                                <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $replyAttachment['type'] ?></span>
                            </div>
                        <?php else : ?>
                            <div class="relative fileicon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="76" height="88" viewBox="0 0 29 32" class="model-attachment" data-identifyElement="367">
                                    <path fill="#ebeff3" d="M3.668.652c-.717 0-1.298.584-1.298 1.304v28.681c0 .72.581 1.304 1.298 1.304h23.365c.717 0 1.298-.584 1.298-1.304V7.545c0-.367-.154-.717-.424-.964L21.799.991a1.294 1.294 0 00-.874-.34H3.668z" data-identifyElement="368"></path>
                                    <path fill="#264966" d="M1.886 10.291l.538.395v5.285L0 13.601v-2.354a1.185 1.185 0 011.886-.956z" data-identifyElement="369"></path>
                                    <path fill="#345c7c" d="M.593 5.6h18.015c.327 0 .593.265.593.593v6.815a.593.593 0 01-.593.593H.001V6.194c0-.327.265-.593.593-.593z" data-identifyElement="370"></path>
                                    <path fill="#b1bdc8" d="M16.921 17.8l-2.625 10.4c-.036.143.049.288.189.325s.283-.049.319-.192l2.625-10.4c.036-.143-.049-.288-.189-.325s-.283.049-.319.192zm3.997 5.126c.207.109.207.41.001.52l-2.586 1.379v1.293l4.738-2.691v-.481l-4.738-2.672v1.283l2.585 1.369zm-10.613.519a.296.296 0 01.001-.52l2.585-1.369v-1.283l-4.738 2.672v.481l4.738 2.691v-1.293l-2.586-1.379z" data-identifyElement="371"></path>
                                </svg>
                                <span class="absolute uppercase left-2 top-4 font-normal text-sm text-white"><?= $replyAttachment['type'] ?></span>
                            </div>
                        <?php endif; ?>
                        <div class="w-full p-4 file-name-size">
                            <span class="font-normal text-sm break-all"><?= $replyAttachment['name']; ?></span><br />
                            <span class="font-normal text-sm"><?= $block->getBytesToKilobytes($replyAttachment['size']) ?></span>
                        </div>
                        <div class="backlayer"></div>
                        <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 download-icon">
                            <a href="<?= $block->getUrl('freshdesk/customer/download', ['file' => urlencode($replyAttachment['url']), 'name' => urlencode($replyAttachment['name'])]) ?>" download>
                                <?= $heroicons->documentDownloadHtml('inline-block w-6 h-6 mr-1', 26, 26, ['title' => 'Download']); ?>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<div x-data="{ open: false }">
    <div class="mt-2">
        <button class="btn btn-primary rounded" title="<?= $block->escapeHtml(__('Reply')) ?>" x-on:click="open = ! open">
            <?= $heroicons->arrowLeftHtml('mr-2 inline', 22, 22); ?>
            <?= $block->escapeHtml(__('Reply')) ?>
        </button>
    </div>
    <div class="mt-10 mb-10" x-show="open">
        <form action="<?php echo $block->getUrl('freshdesk/customer/reply') ?>" id="reply-form" class="form form-edit-account card" method="post" enctype="multipart/form-data">
            <input type="hidden" name="ticket_id" value="<?php echo $ticketId; ?>">
            <?php if ($ticketStatusCode === 5) : ?>
                <input type="hidden" name="ticket_status" value="<?php echo $ticketStatusCode; ?>">
            <?php endif; ?>
            <?= $block->getBlockHtml('formkey'); ?>
            <div class="mt-2">
                <textarea name="reply_message" id="reply_message" rows="5" class="input input-light w-full" placeholder="Enter your reply message"></textarea>
            </div>
            <div class="mt-2">
                <label for="attachments"><?php echo __('Attachments') ?></label>
                <input name="attachments[]" id="attachments" type="file" class="input input-light w-full" multiple />
                <div class="text-sm text-gray-600 mt-1">
                    <?php echo __('Allowed file types: jpg, png, pdf. Maximum size: 20 MB'); ?>
                </div>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-primary" name="send" id="send2"><?php echo __('Send') ?></button>
            </div>
        </form>
    </div>
</div>

<style type="text/css">
    .attachment:hover .backlayer {
        opacity: 1;
    }

    .attachment .backlayer {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        opacity: 0;
        transition: .1s ease-in;
        border-radius: 4px;
        background-image: linear-gradient(to left, #fff, #fff 47%, rgba(255, 255, 255, 0));
    }

    .attachment .download-icon {
        transition: opacity 0.3s ease;
        opacity: 0;
    }

    .attachment:hover .download-icon {
        opacity: 1;
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        tinymce.init({
            selector: '#reply_message',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });

        var replyMsg = "<?php echo $replyMsg; ?>";

        document.getElementById('reply-form').addEventListener('submit', function(event) {
            const replyMessageContent = tinymce.get('reply_message').getContent({
                format: 'text'
            }).trim();
            if (replyMessageContent === '') {
                alert(replyMsg);
                event.preventDefault();
                tinymce.get('reply_message').focus();
            }
        });
    });
</script>
