<?php

use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Post $post */
$post = $this->getPost();
?>

<a href="<?php echo $post->getPostUrl() ?>" class="flex flex-col border-b">
    <div class="training-item-media">
        <?php if ($featuredImage = $post->getFeaturedImage()) : ?>
            <img src="<?php echo $featuredImage ?>" class="w-full">
        <?php endif; ?>
    </div>

    <div class=" training-item-wrapper flex flex-col gap-8 py-8">
        <div class="training-item-text">
            <h3 class="text-xl font-bold mb-2">
                <?php echo $block->escapeHtml($post->getTitle(), null, true); ?>
            </h3>
            <div class="prose">
                <?php echo $block->getShortContent() ?>
            </div>
        </div>

        <div class="training-item-details flex flex-col">
            <span>
                <?= $heroicons->calendarHtml("h-6 w-6 border-current inline", 25, 25) ?>
                <?php echo $post->getPublishDate('d/m/Y') ?>
            </span>
            <span>
                <?= $heroicons->clockHtml("h-6 w-6 border-current inline", 25, 25) ?>
                <?php echo $post->getHour() ?>
            </span>
            <span>
                <?= $heroicons->locationMarkerHtml("h-6 w-6 border-current inline", 25, 25) ?>
                <?php echo $post->getLocation(); ?>
            </span>
            <span>
                <?= $heroicons->userGroupHtml("h-6 w-6 border-current inline", 25, 25) ?>
                <?php echo __('Nog %1 plaatsen vrij', $post->getRemainingPlaces()); ?>
            </span>
        </div>

        <div>
            <div class="btn inline">
                <?php echo __('Nu inschrijven'); ?>
            </div>
        </div>
    </div>
</a>
