<div>
    <?php $collection = $block->getPostCollection(); ?>
    <?php $categories = $block->getCategories(); ?>

    <?php if ($categories->getSize() > 0) : ?>
        <div id="filterBoxCover" class="mb-6 relative z-10">
            <form method="get" action="" class="form contact filterBox">
                <div class="field name flex flex-col lg:flex-row gap-5 lg:gap-8 items-center flex-nowrap">
                    <label for="category" class="label"><?php echo __('Welke opleiding zoekt u?'); ?></label>
                    <?php $categoryText = null; ?>
                    <?php if (isset($_REQUEST['category']) != null) {
                        $categoryID = $_REQUEST['category'];
                        $categories1 = $block->getCategories()->addFieldToFilter('category_id', $categoryID);
                        foreach ($categories1 as $item) {
                            $categoryText = $item['title'];
                        }
                    }
                    ?>
                    <div x-data="{ selectedText: '<?php echo $categoryText; ?>', selectedId: null, showDropdown: false }" class="relative z-0">
                        <button type="button" @click="showDropdown = !showDropdown" class="relative bg-white pl-5 pr-14 pt-2 pb-1.5 border border-gray-300 italic flex items-center justify-center min-w-[265px]">
                            <span class="block" x-text="selectedText || '<?php echo __('Selecteer productcategorie') ?>'"></span>
                            <input type="hidden" name="category" :value="selectedId">
                            <span class="dropdownIcon" :class="showDropdown ? 'iconUp' : 'iconDown'"></span>
                        </button>

                        <ul x-show="showDropdown" @click="showDropdown = false" @click.away="showDropdown = false" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 scale-90" x-transition:enter-end="opacity-100 scale-100" x-transition:leave="transition ease-in duration-300" x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-90" class="dropdown-menu absolute z-100">
                            <li id="0">
                                <a href="javascript:void(0)" :class="{ 'active': selectedText === '<?php echo __('Selecteer productcategorie') ?>' }" @click="selectedText = null; selectedId = null">
                                    <?php echo __('Selecteer productcategorie') ?>
                                </a>
                            </li>
                            <?php foreach ($categories as $category) : ?>
                                <li id="<?php echo $category->getId(); ?>">
                                    <a href="javascript:void(0)" :class="{ 'active': selectedText === '<?php echo $category->getTitle(); ?>' }" @click="selectedText = '<?php echo $category->getTitle(); ?>'; selectedId = '<?php echo $category->getId(); ?>'">
                                        <?php echo $category->getTitle(); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="buttonBox">
                        <button class="btn btn-primary uppercase" type="submit" onclick="this.form.submit()"><?php echo __('Bevestig') ?></button>
                    </div>
                </div>
            </form>
        </div>
    <?php endif; ?>

    <?php if (!$collection->count()) : ?>
        <div class="message info empty">
            <div><?php echo __('No trainings found.') ?></div>
        </div>
    <?php else : ?>
        <div class="trainingBlocks allAccordionCover pb-5">
            <?php foreach ($collection as $post) : ?>
                <div class="singleBox" x-data="{ open: false }">
                    <div class="accordTitle" x-on:click="open = !open">
                        <div class="imageBlock">
                            <?php if ($homeImage = $post->getHomeImage()) : ?>
                                <img src="<?php echo $homeImage ?>">
                            <?php endif; ?>
                        </div>
                        <div class="trainingTitle">
                            <h3><?php echo $block->escapeHtml($post->getTitle(), null, true); ?> | <?php echo $post->getPublishDate('d-m-Y') ?> | <?php echo $this->helper('Newance\Training\Helper\Data')->getStoreNameById($post->getStoreId()) ?></h3>
                            <div class="smallDetails w-full mt-3">
                                <ul class="smallDetailsList flex items-center">
                                    <li class="listItem">
                                        <span class="detailIcon">
                                            <svg id="Laag_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.46 283.46" class="h-6 w-6 border-current inline">
                                                <path class="cls-2" fill="#1d1d1b" d="m14.17,242.63c0,3.83,3.1,6.93,6.93,6.93h241.25c3.83,0,6.93-3.1,6.93-6.93V90.81H14.17v151.82Z"></path>
                                                <path class="cls-2" fill="#1d1d1b" d="m262.36,45.74h-27.38v14.73h-16.64v-14.73H65.13v14.73h-16.64v-14.73h-27.38c-3.83,0-6.93,3.1-6.93,6.93v33.28h255.12v-33.28c0-3.83-3.1-6.93-6.93-6.93Z"></path>
                                                <rect class="cls-2" fill="#1d1d1b" x="51.16" y="33.9" width="10.98" height="23.68"></rect>
                                                <rect class="cls-2" fill="#1d1d1b" x="221.08" y="33.9" width="10.98" height="23.68"></rect>
                                                <rect class="cls-1" fill="#fff" x="161.43" y="113.34" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="194.93" y="113.34" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="228.42" y="113.34" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="161.43" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="194.93" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="228.42" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="161.43" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="194.93" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="228.42" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="161.43" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="194.93" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="228.42" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="62.14" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="95.63" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="129.12" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="62.14" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="95.63" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="129.12" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="62.14" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="95.63" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="129.12" y="202.64" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="30.36" y="143.1" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="30.36" y="172.87" width="20.8" height="20.8"></rect>
                                                <rect class="cls-1" fill="#fff" x="30.36" y="202.64" width="20.8" height="20.8"></rect>
                                            </svg>
                                        </span>
                                        <span class="detailText"><?php echo $post->getPublishDate('d/m/Y') ?></span>
                                    </li>
                                    <li class="listItem">
                                        <span class="detailIcon">
                                            <svg id="Laag_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.46 283.46" class="h-6 w-6 border-current inline">
                                                <circle class="cls-1" fill="transparent" stroke="#1d1d1b" stroke-miterlimit="10" stroke-width="15.55" cx="141.73" cy="141.73" r="113.39"></circle>
                                                <line class="cls-2" fill="transparent" stroke="#1d1d1b" stroke-miterlimit="10" stroke-width="15.55" stroke-linecap="round" x1="92.22" y1="187.27" x2="141.73" y2="141.73"></line>
                                                <line class="cls-2" fill="transparent" stroke="#1d1d1b" stroke-miterlimit="10" stroke-width="15.55" stroke-linecap="round" x1="220.74" y1="116.55" x2="141.73" y2="141.73"></line>
                                            </svg>
                                        </span>
                                        <span class="detailText"><?php echo $post->getHour() ?></span>
                                    </li>
                                    <li class="listItem">
                                        <span class="detailIcon">
                                            <svg id="Laag_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.46 283.46" class="h-7 w-7 border-current inline">
                                                <path class="cls-1" fill="#1d1d1b" d="m141.73,28.35c-45.69,0-82.73,37.04-82.73,82.73,0,18.67,6.26,35.83,16.69,49.68l63.93,94.36,64.52-89.83c12.63-14.53,20.33-33.45,20.33-54.21,0-45.69-37.04-82.73-82.73-82.73Zm0,108.25c-17.7,0-32.04-14.35-32.04-32.04s14.35-32.04,32.04-32.04,32.04,14.35,32.04,32.04-14.35,32.04-32.04,32.04Z"></path>
                                            </svg>
                                        </span>
                                        <span class="detailText"><?php echo $post->getLocation() ?></span>
                                    </li>
                                    <li class="listItem">
                                        <span class="detailIcon">
                                            <svg id="Laag_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.46 283.46" class="h-8 w-8 border-current inline">
                                                <path class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" d="m82.39,129.82c-29.85,0-54.05,24.2-54.05,54.05h108.09c0-29.85-24.2-54.05-54.05-54.05Z"></path>
                                                <circle class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" cx="82.39" cy="102.76" r="24.6"></circle>
                                                <path class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" d="m201.07,128.63c-29.85,0-54.05,24.2-54.05,54.05h108.09c0-29.85-24.2-54.05-54.05-54.05Z"></path>
                                                <circle class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" cx="201.07" cy="101.56" r="24.6"></circle>
                                                <path class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" d="m141.99,152.45c-29.85,0-54.05,24.2-54.05,54.05h108.09c0-29.85-24.2-54.05-54.05-54.05Z"></path>
                                                <circle class="cls-1" fill="#1d1d1b" stroke="#fff" stroke-miterlimit="10" stroke-width="5.24" cx="141.99" cy="125.38" r="24.6"></circle>
                                            </svg>
                                        </span>
                                        <span class="detailText"><?php echo __('%1 plaatsen', $post->getRemainingPlaces()); ?></span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="buttonBox">
                            <a href="<?php echo $post->getPostUrl() ?>" class="btn btn-primary uppercase"><?php echo __('Inschrijven'); ?></a>
                            <a href="javascript:void(0)" class="dummyLink">
                                <span :class="open ? 'hidden' : ''"><?php echo __('More info') ?></span>
                                <span :class="open ? '' : 'hidden'"><?php echo __('Less info') ?></span>
                                <span class="icon" :class="open ? 'iconUp' : 'iconDown'">
                                    <!-- &#8735; -->
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="accordDesc" x-show="open" x-transition>
                        <?php echo $post->getHomeShortContent() ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <div class="text-center mt-8 mb-4">
            <a href="<?php echo $block->getUrl('trainings') ?>" class="btn btn-primary inline">
                <?php echo __('Klik hier voor het volledige opleidingsaanbod'); ?>
            </a>
        </div>
    <?php endif; ?>
</div>
